# Generated by Django 4.1.6 on 2023-03-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.TextField(),
        ),
    ]
