# Generated by Django 4.1.6 on 2023-03-23 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='date',
        ),
        migrations.AddField(
            model_name='list',
            name='date_field',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 21, 34, 38, 2364, tzinfo=datetime.timezone.utc)),
        ),
    ]
