# Generated by Django 4.1.6 on 2023-03-23 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_list_date_field_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 21, 52, 2, 812583, tzinfo=datetime.timezone.utc)),
        ),
    ]
