# Generated by Django 4.1.6 on 2023-03-23 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 21, 55, 0, 333272, tzinfo=datetime.timezone.utc)),
        ),
    ]
