# Generated by Django 4.1.6 on 2023-03-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_list_date_alter_list_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default='March 23, 2023 04:24 PM'),
        ),
    ]
