# Generated by Django 4.1.6 on 2023-03-24 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_category_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 18, 0, 13, 321044, tzinfo=datetime.timezone.utc)),
        ),
    ]
