# Generated by Django 4.1.6 on 2023-03-24 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 18, 13, 14, 70846, tzinfo=datetime.timezone.utc)),
        ),
    ]
