# Generated by Django 4.1.6 on 2023-03-24 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_list_categories_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 11, 57, 34, 959956, tzinfo=datetime.timezone.utc)),
        ),
    ]
