# Generated by Django 4.1.6 on 2023-03-26 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_alter_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='closed',
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 16, 8, 10, 947917, tzinfo=datetime.timezone.utc)),
        ),
    ]
