# Generated by Django 4.1.6 on 2023-03-27 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_remove_list_closed_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 19, 52, 18, 328143, tzinfo=datetime.timezone.utc)),
        ),
    ]
