# Generated by Django 4.1.6 on 2023-03-27 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_alter_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='closed',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 19, 53, 47, 469711, tzinfo=datetime.timezone.utc)),
        ),
    ]
