# Generated by Django 4.1.6 on 2023-03-28 01:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_list_closed_alter_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 19, 57, 44, 579943, tzinfo=datetime.timezone.utc)),
        ),
    ]
